Repository sktime/skpro, pull requests merged in 2023-10, with the labels that each got.

#111 [MNT] address deprecation of `skbase.testing.utils.deep_equals`
  skpro/tests/test_all_estimators.py
Labels: maintenance

#110 [MNT] activate `dependabot` for version updates and maintenance
  .github/dependabot.yml
Labels: maintenance

#89 [ENH] basic "test all estimators" suite
  skpro/tests/scenarios/__init__.py
  skpro/tests/scenarios/scenarios.py
  skpro/tests/scenarios/scenarios_getter.py
  skpro/tests/scenarios/scenarios_regressor_proba.py
  skpro/tests/test_all_estimators.py
  skpro/utils/random_state.py
Labels: enhancement, module:tests

#119 Release 2.0.1
  docs/source/_static/switcher.json
  docs/source/changelog.rst
  pyproject.toml
  skpro/__init__.py
Labels: maintenance, release

#120 Release 2.1.0
  docs/source/_static/switcher.json
  docs/source/changelog.rst
  pyproject.toml
  skpro/__init__.py
Labels: maintenance, release

#123 [MNT] simplify wheels test for release
  .github/workflows/wheels.yml
Labels: maintenance, release

#124 [MNT] fix wheels test for release
  .github/workflows/wheels.yml
Labels: maintenance

#125 [MNT] point readthedocs `json` switcher variable to GitHub
  docs/source/conf.py
Labels: maintenance

#121 [DOC] fix math in `plotting` docstrings
  skpro/utils/plotting.py
Labels: documentation

#126 [MNT] change test OS versions to latest
  .github/workflows/test.yml
Labels: maintenance

#129 [ENG] probabilistic regressors - input checks and support for more input types
  skpro/registry/_tags.py
  skpro/regression/base/_base.py
Labels: enhancement, module:base-framework, implementing framework

#108 [ENH] multiple quantile regression
  .all-contributorsrc
  docs/source/api_reference/regression.rst
  skpro/regression/multiquantile.py
Labels: enhancement, module:regression, implementing algorithms

#137 [ENH] improved probabilistic tabular regressor extension template
  extension_templates/regression.py
Labels: enhancement, module:regression, documentation

#138 [ENH] integrate `check_estimator` with `TestAllEstimators` and `TestAllRegressors` for python command line estimator testing
  skpro/tests/test_all_estimators.py
  skpro/utils/estimator_checks.py
Labels: enhancement, module:tests

#139 [DOC] typo fixes in regression extension template
  extension_templates/regression.py
Labels: module:regression, documentation

#140 [ENH] improved conditional testing
  skpro/tests/test_all_estimators.py
  skpro/tests/test_switch.py
  skpro/utils/validation/_dependencies.py
Labels: enhancement, module:tests

#142 [BUG] fix test fixture generation logic
  skpro/distributions/tests/test_all_distrs.py
  skpro/regression/tests/test_all_regressors.py
Labels: bug, module:tests
