Repository sktime/skpro, pull requests merged in 2023-08, with the labels that each got.

#19 [ENH] Laplace distribution
  skpro/distributions/__init__.py
  skpro/distributions/laplace.py
Labels: enhancement

#24 [ENH] minor improvements to probability distribution tests
  skpro/distributions/tests/test_all_distrs.py
Labels: enhancement, module:probability&simulation

#34 [BUG] fix distribution suite test class missing package config
  skpro/distributions/tests/test_all_distrs.py
Labels: bug, maintenance, module:base-framework

#25 [ENH] empirical distribution
  skpro/distributions/__init__.py
  skpro/distributions/empirical.py
  skpro/distributions/laplace.py
Labels: enhancement, module:probability&simulation, implementing algorithms

#26 [ENH] mixture of distributions
  skpro/distributions/__init__.py
  skpro/distributions/base.py
  skpro/distributions/mixture.py
  skpro/tests/test_all_estimators.py
Labels: enhancement, module:probability&simulation, implementing algorithms

#36 [MNT] remove deprecated `load_boston` loader from `sklearn`
  examples/custom_model.py
  examples/parametric/hyperparameters.py
  examples/parametric/simple.py
  examples/simple.py
  skpro/workflow/manager/data.py
Labels: maintenance

#35 [MNT] update `sklearn` bound to `<1.4.0`
  pyproject.toml
  skpro/tests/test_baselines.py
  skpro/tests/test_parametric.py
  skpro/tests/utils.py
Labels: maintenance

#37 [ENH] tuning and simple benchmarking
  skpro/base/_base.py
  skpro/benchmarking/__init__.py
  skpro/benchmarking/evaluate.py
  skpro/benchmarking/tests/__init__.py
  skpro/benchmarking/tests/test_evaluate.py
  skpro/model_selection/__init__.py
  skpro/model_selection/_tuning.py
  skpro/regression/base/__init__.py
  skpro/regression/base/_base.py
  skpro/regression/base/_delegate.py
Labels: enhancement, module:regression, implementing algorithms

#43 [ENH] add test for subsetting distributions
  skpro/distributions/empirical.py
  skpro/distributions/tests/test_all_distrs.py
  skpro/utils/index.py
Labels: enhancement, module:probability&simulation

#41 [ENH] turn off sorting in `groupby`-s
  skpro/distributions/base.py
  skpro/distributions/empirical.py
Labels: enhancement, module:probability&simulation, implementing framework

#39 [ENH] adds bootstrap probabilistic regressor
  skpro/regression/base/_base.py
  skpro/regression/bootstrap.py
Labels: enhancement, module:regression, implementing algorithms

#44 [ENH] registry module with lookup and tag register
  skpro/distributions/base.py
  skpro/metrics/base.py
  skpro/registry/__init__.py
  skpro/registry/_lookup.py
  skpro/registry/_tags.py
  skpro/regression/base/_base.py
  skpro/tests/test_all_estimators.py
Labels: enhancement, module:base-framework

#48 [DOC] replace leftover `sktime` references in docstrings and utilities with `skpro`
  .github/workflows/test.yml
  extension_templates/regression.py
  setup.cfg
  skpro/base/__init__.py
  skpro/benchmarking/evaluate.py
  skpro/datatypes/_check.py
  skpro/datatypes/_common.py
  skpro/datatypes/_convert.py
  skpro/datatypes/_examples.py
  skpro/datatypes/_registry.py
  skpro/distributions/base.py
  skpro/distributions/empirical.py
  skpro/distributions/normal.py
  skpro/distributions/tests/__init__.py
  skpro/distributions/tests/test_all_distrs.py
  skpro/metrics/_coerce.py
  skpro/metrics/base.py
  skpro/registry/_lookup.py
  skpro/utils/_maint/_show_versions.py
  skpro/utils/_maint/tests/test_show_versions.py
  skpro/utils/validation/_dependencies.py
Labels: maintenance, documentation

#47 [BUG] fix missing `np.abs` in `ResidualDouble`
  skpro/regression/residual.py
Labels: bug, module:regression

#46 [ENH] diagnostic plots part 1 - cross-plots
  examples/utils.py
  skpro/utils/plotting.py
  skpro/utils/tests/__init__.py
  skpro/utils/tests/test_plots.py
Labels: enhancement, module:regression

#49 [ENH] Student's t-distribution
  skpro/distributions/t.py
Labels: enhancement, module:probability&simulation, implementing algorithms

#51 [ENH] pipeline
  skpro/registry/_tags.py
  skpro/regression/base/_base.py
  skpro/regression/compose/__init__.py
  skpro/regression/compose/_pipeline.py
Labels: enhancement, module:regression, implementing framework

#52 [ENH] add specification test for the tag registry
  skpro/registry/tests/__init__.py
  skpro/registry/tests/test_tags.py
Labels: enhancement, module:base-framework

#50 [ENH] adds `.all-contributorsrc` file with current contributors
  .all-contributorsrc
Labels: enhancement, documentation

#54 [ENH] Refactor of BaseDistribution and descendants - generalised distribution param broadcasting in base class
  skpro/distributions/base.py
  skpro/distributions/laplace.py
  skpro/distributions/normal.py
  skpro/distributions/t.py
  skpro/distributions/tests/test_base_default_methods.py
Labels: enhancement, module:probability&simulation, implementing framework
