Repository sktime/skpro, pull requests merged in 2024-11, with the labels that each got.

#487 [DOC] in docstring, rename `Example` to `Examples` sections
  skpro/distributions/alpha.py
  skpro/distributions/beta.py
  skpro/distributions/binomial.py
  skpro/distributions/chi_squared.py
  skpro/distributions/compose/_iid.py
  skpro/distributions/delta.py
  skpro/distributions/empirical.py
  skpro/distributions/fisk.py
  skpro/distributions/gamma.py
  skpro/distributions/halfcauchy.py
  skpro/distributions/halflogistic.py
  skpro/distributions/halfnormal.py
  skpro/distributions/inversegamma.py
  skpro/distributions/laplace.py
  skpro/distributions/logistic.py
  skpro/distributions/loglaplace.py
  skpro/distributions/lognormal.py
  skpro/distributions/meanscale.py
  skpro/distributions/mixture.py
  skpro/distributions/normal.py
  skpro/distributions/pareto.py
  skpro/distributions/poisson.py
  skpro/distributions/qpd.py
  skpro/distributions/qpd_empirical.py
  skpro/distributions/t.py
  skpro/distributions/truncated_normal.py
  skpro/distributions/uniform.py
  skpro/distributions/weibull.py
  skpro/regression/cyclic_boosting.py
  skpro/regression/mapie.py
  skpro/regression/residual.py
  skpro/utils/plotting.py
Labels: documentation

#490 [ENH] Synchronize dependency checker with `sktime` counterpart
  .all-contributorsrc
  skpro/utils/_maint/_show_versions.py
  skpro/utils/_maint/tests/test_show_versions.py
  skpro/utils/validation/_dependencies.py
Labels: enhancement, module:base-framework

#358 [ENH] Creating a new Bayesian Regressor with PyMC as a backend
  .all-contributorsrc
  pyproject.toml
  skpro/regression/bayesian.py
Labels: enhancement, module:regression

#495 Release 2.8.0
  .all-contributorsrc
  CODEOWNERS
  README.md
  docs/source/_static/switcher.json
  docs/source/changelog.rst
  pyproject.toml
  skpro/__init__.py
  skpro/base/_base.py
Labels: maintenance, release

#496 [ENH] set up exclude list for estimators
  skpro/tests/_config.py
  skpro/tests/test_all_estimators.py
Labels: enhancement, module:tests
