Repository sktime/skpro, pull requests merged in 2024-06, with the labels that each got.

#371 [ENH] Half Cauchy Distribution
  docs/source/api_reference/distributions.rst
  skpro/distributions/__init__.py
  skpro/distributions/halfcauchy.py
Labels: enhancement, module:probability&simulation, interfacing algorithms

#373 [ENH] Half Logistic Distribution
  docs/source/api_reference/distributions.rst
  skpro/distributions/__init__.py
  skpro/distributions/halflogistic.py
Labels: enhancement, module:probability&simulation, implementing algorithms

#381 [BUG] fix `test_methods_p` logic when `shuffle` is `True`
  skpro/distributions/tests/test_all_distrs.py
Labels: bug, module:probability&simulation, module:tests

#386 [BUG] - bugfix when `None` was specified for `max_iter` parameter in sklearn regressors
  skpro/regression/linear/_sklearn.py
Labels: bug, module:regression

#388 [BUG] bugfix on #387 - changed paramset 3 to use `ConditionUncensored` instead of `CoxPH`
  skpro/model_selection/_tuning.py
Labels: bug, module:regression, module:survival&time-to-event

#391 [ENH] interval width and area under calibration curve metrics
  docs/source/api_reference/metrics.rst
  skpro/metrics/__init__.py
  skpro/metrics/_classes.py
  skpro/metrics/tests/test_probabilistic_metrics.py
Labels: enhancement, implementing algorithms, module:metrics&benchmarking

#384 [ENH] `GLM` with multiple `distributions` and `link` function support
  skpro/regression/linear/_glm.py
  skpro/regression/tests/test_glm.py
Labels: enhancement, module:regression, interfacing algorithms

#370 [ENH] Introducing test file for polars support for estimators
  skpro/regression/base/_base.py
  skpro/tests/test_polars.py
Labels: enhancement, module:datatypes

#396 [ENH] Pareto distribution
  docs/source/api_reference/distributions.rst
  skpro/distributions/__init__.py
  skpro/distributions/pareto.py
Labels: enhancement, module:probability&simulation, implementing algorithms

#379 [DOC] add `scipy` reference to interfaced distributions
  skpro/distributions/alpha.py
  skpro/distributions/beta.py
  skpro/distributions/exponential.py
  skpro/distributions/fisk.py
  skpro/distributions/gamma.py
  skpro/distributions/halfcauchy.py
  skpro/distributions/halflogistic.py
  skpro/distributions/halfnormal.py
  skpro/distributions/loglaplace.py
  skpro/distributions/poisson.py
Labels: module:probability&simulation, documentation

#400 [DOC] in API reference, order distributions by support
  docs/source/api_reference/distributions.rst
Labels: module:probability&simulation, documentation

#401 [MNT] make `BaseArrayDistribution` private
  docs/source/api_reference/distributions.rst
  skpro/distributions/base/__init__.py
  skpro/distributions/base/_base_array.py
  skpro/distributions/histogram.py
Labels: maintenance, module:probability&simulation

#403 [BUG] ensure `index` and `columns` are taken into account in broadcasting if `bc_params` are set
  skpro/distributions/base/_base.py
Labels: bug, module:probability&simulation

#282 [ENH] mean-scale family of distributions, composite
  docs/source/api_reference/distributions.rst
  skpro/distributions/__init__.py
  skpro/distributions/base/_base.py
  skpro/distributions/meanscale.py
Labels: enhancement, module:probability&simulation

#402 Release 2.3.2
  README.md
  docs/source/_static/switcher.json
  docs/source/changelog.rst
  pyproject.toml
  skpro/__init__.py
Labels: maintenance, release

#393 [MNT] increase `numpy` bound to `numpy < 2.1`, `numpy 2` compatibility
  pyproject.toml
Labels: maintenance, release

#404 [MNT] 2.4.0 deprecations and change actions
  skpro/regression/cyclic_boosting.py
  skpro/regression/linear/_glm.py
Labels: maintenance, release

#406 Release 2.4.0
  README.md
  docs/source/_static/switcher.json
  docs/source/changelog.rst
  pyproject.toml
  skpro/__init__.py
Labels: maintenance, release

#407 [MNT] `scipy 1.14` compatibility patch
  skpro/regression/density.py
  skpro/tests/test_density.py
Labels: maintenance

#411 Release 2.4.1
  README.md
  docs/source/_static/switcher.json
  docs/source/changelog.rst
  pyproject.toml
  skpro/__init__.py
Labels: maintenance, release

#415 [ENH] Added Inverse Gamma distribution
  docs/source/api_reference/distributions.rst
  skpro/distributions/__init__.py
  skpro/distributions/binomial.py
  skpro/distributions/inversegamma.py
Labels: enhancement, module:probability&simulation, implementing algorithms, interfacing algorithms

#414 [BUG] Histogram Distribution: address `np.broadcast_arrays` deprecation of writable return in `numpy 2.0.0`
  skpro/distributions/base/_base_array.py
Labels: bug, module:probability&simulation
