Repository sktime/skpro, pull requests merged in 2024-08, with the labels that each got.

#437 [ENH] `DummyProbaRegressor` - probabilistic dummy regressor
  docs/source/api_reference/regression.rst
  skpro/regression/dummy.py
  skpro/regression/linear/__init__.py
Labels: enhancement, module:regression, implementing algorithms

#441 Release 2.4.2
  README.md
  docs/source/_static/switcher.json
  docs/source/changelog.rst
  pyproject.toml
  skpro/__init__.py
Labels: maintenance, release

#443 [MNT] 2.5.0 deprecations and change actions
  skpro/distributions/qpd.py
  skpro/model_selection/_tuning.py
  skpro/regression/linear/_glm.py
Labels: maintenance, release

#446 [MNT] ensure `CyclicBoosting` is consistent with deprecations in `QPD_Johnson`
  skpro/regression/cyclic_boosting.py
Labels: maintenance

#445 [MNT] release workflow: Upgrade deprecated pypa action parameter #6878
  .github/workflows/wheels.yml
Labels: maintenance

#433 [MNT] python 3.8 end-of-life - remove 3.8 support
  .github/workflows/test.yml
  .github/workflows/wheels.yml
  pyproject.toml
  skpro/base/_base.py
Labels: maintenance, release

#444 Release 2.5.0
  README.md
  docs/source/_static/switcher.json
  docs/source/changelog.rst
  pyproject.toml
  skpro/__init__.py
Labels: maintenance, release

#448 [BUG] changelog utility: fix termination condition to retrieve merged PR
  build_tools/changelog.py
Labels: bug, maintenance

#452 [BUG] Update `skpro.utils.git_diff` to fix issue with encoding
  skpro/utils/git_diff.py
Labels: bug, maintenance, module:tests

#451 [DOC] minor updates to `README.md`
  README.md
Labels: documentation
