Repository sktime/skpro, pull requests merged in 2024-05, with the labels that each got.

#215 [ENH] interface to `ngboost`
  .all-contributorsrc
  docs/source/api_reference/regression.rst
  pyproject.toml
  skpro/regression/gradient_boosting/__init__.py
  skpro/regression/gradient_boosting/_ngboost.py
Labels: enhancement, module:regression, interfacing algorithms

#287 [ENH] Adapter for Scipy Distributions
  skpro/distributions/adapters/scipy/__init__.py
  skpro/distributions/adapters/scipy/_distribution.py
  skpro/distributions/adapters/scipy/tests/test_scipy_adapters.py
  skpro/distributions/fisk.py
  skpro/distributions/poisson.py
Labels: enhancement, module:probability&simulation

#297 [MNT] fix binder environment
  .binder/Dockerfile
Labels: maintenance, documentation

#293 [ENH] simplify coercion in `BaseDistribution._log_pdf` and `_pdf` default
  skpro/distributions/base/_base.py
Labels: enhancement, module:probability&simulation

#295 [ENH] distributions: `pmf` and `log_pmf` method
  skpro/distributions/adapters/scipy/_distribution.py
  skpro/distributions/adapters/scipy/tests/test_scipy_adapters.py
  skpro/distributions/base/_base.py
  skpro/distributions/tests/test_all_distrs.py
  skpro/tests/test_all_estimators.py
Labels: enhancement, module:probability&simulation

#299 [ENH] delta distribution
  docs/source/api_reference/distributions.rst
  skpro/distributions/__init__.py
  skpro/distributions/delta.py
Labels: enhancement, module:probability&simulation

#300 [ENH] Delta point prediction baseline regressor
  docs/source/api_reference/regression.rst
  skpro/distributions/delta.py
  skpro/regression/delta.py
Labels: enhancement, module:regression, implementing algorithms

#296 [ENH] faster collection of differential tests through caching, test if pyproject change
  skpro/tests/_config.py
  skpro/tests/_config_test_dummy.py
  skpro/tests/test_switch.py
  skpro/tests/tests/__init__.py
  skpro/tests/tests/test_test_utils.py
  skpro/utils/git_diff.py
Labels: maintenance, module:tests

#298 [ENH] Beta Distribution
  docs/source/api_reference/distributions.rst
  skpro/distributions/__init__.py
  skpro/distributions/beta.py
Labels: enhancement, module:probability&simulation

#302 [ENH] moving ensemble regressors to `regression.ensemble`
  docs/source/api_reference/regression.rst
  skpro/regression/ensemble/__init__.py
  skpro/regression/ensemble/_bagging.py
  skpro/regression/ensemble/_ngboost.py
  skpro/regression/gradient_boosting/__init__.py
Labels: maintenance, module:regression, documentation

#294 [ENH] distributions: survival and hazard function and defaults
  skpro/distributions/base/_base.py
  skpro/distributions/tests/test_all_distrs.py
Labels: enhancement, module:probability&simulation

#306 [BUG] fix `CoxPH` handling of `statsmodels` `status` variable
  skpro/distributions/adapters/statsmodels/_empirical.py
  skpro/survival/coxph/_coxph_statsmodels.py
Labels: bug, module:survival&time-to-event

#307 [ENH] improved `Empirical` distribution - scalar mode, new API compatibility
  skpro/distributions/empirical.py
Labels: enhancement, module:probability&simulation

#308 [ENH] increase distribution default `plot` resolution
  skpro/distributions/base/_base.py
Labels: enhancement, module:probability&simulation

#285 [ENH] distribution `get_params` in data frame format
  skpro/distributions/adapters/scipy/_distribution.py
  skpro/distributions/base/_base.py
  skpro/distributions/beta.py
  skpro/distributions/chi_squared.py
  skpro/distributions/delta.py
  skpro/distributions/empirical.py
  skpro/distributions/fisk.py
  skpro/distributions/laplace.py
  skpro/distributions/logistic.py
  skpro/distributions/lognormal.py
  skpro/distributions/mixture.py
  skpro/distributions/normal.py
  skpro/distributions/poisson.py
  skpro/distributions/t.py
  skpro/distributions/tests/test_proba_basic.py
  skpro/distributions/uniform.py
  skpro/distributions/weibull.py
  skpro/registry/_tags.py
Labels: enhancement, module:probability&simulation

#303 [DOC] tutorial notebook for probability distributions
  README.md
  examples/03_skpro_distributions.ipynb
Labels: module:probability&simulation, documentation

#310 [ENH] `head` and `tail` for distribution objects
  skpro/distributions/base/_base.py
  skpro/distributions/tests/test_proba_basic.py
Labels: enhancement, module:probability&simulation

#314 [ENH] full support of hierarchical `MultiIndex` `index` in `Empirical` distirbution, tests
  skpro/distributions/empirical.py
Labels: enhancement, module:probability&simulation

#309 [MNT] refactor `NGBoostRegressor` to inherit `NGBoostAdapter`
  skpro/regression/ensemble/_ngboost.py
Labels: enhancement, module:regression

#315 [ENH] `Mixture` distribution upgrade - refactor to new extension interface, support scalar case
  skpro/distributions/base/_base.py
  skpro/distributions/mixture.py
Labels: enhancement, module:probability&simulation

#316 [BUG] fix survival metrics if `C_true=None` is passed
  skpro/metrics/base.py
  skpro/metrics/survival/_c_harrell.py
  skpro/metrics/survival/tests/test_c_harrell.py
Labels: bug, module:metrics&benchmarking

#318 [ENH] in `ConditionUncensored` reducer, ensure coercion to float of `C`
  skpro/survival/compose/_reduce_cond_unc.py
Labels: enhancement, module:survival&time-to-event

#305 [DOC] tutorial notebook for survival prediction
  examples/02_skpro_survival.ipynb
Labels: documentation, module:survival&time-to-event

#311 [DOC] visualizations for first intro vignette in intro notebook and minor updates
  examples/01_skpro_intro.ipynb
Labels: module:regression, documentation

#317 [DOC] improve docstrings of metrics
  skpro/metrics/base.py
  skpro/metrics/survival/_c_harrell.py
  skpro/metrics/survival/_spll.py
Labels: documentation, module:metrics&benchmarking

#232 [ENH] update Johnson QPDistributions with bugfixes and vectorization (cyclic-boosting ver.1.4.0)
  docs/source/api_reference/distributions.rst
  pyproject.toml
  skpro/distributions/__init__.py
  skpro/distributions/qpd.py
  skpro/distributions/tests/test_qpd.py
  skpro/regression/cyclic_boosting.py
  skpro/regression/tests/test_cyclic_boosting.py
Labels: bug, module:probability&simulation

#328 [MNT] remove `findiff` soft dependency
  pyproject.toml
Labels: maintenance

#331 [BUG] `BaseDistribution._var`: fix missing factor 2 in Monte Carlo variance default method
  skpro/distributions/base/_base.py
Labels: bug, module:probability&simulation

#330 [ENH] improved defaults for `BaseDistribution` `_mean`, `_var`, and `_energy_x`
  skpro/distributions/base/_base.py
Labels: enhancement, module:probability&simulation

#332 [MNT] `Exponential` dist in `NGBoostRegressor`, `NGBoostSurvival`
  skpro/regression/adapters/ngboost/_ngboost_proba.py
  skpro/regression/ensemble/_ngboost.py
  skpro/survival/ensemble/_ngboost_surv.py
Labels: enhancement, module:regression, module:survival&time-to-event

#327 [ENH] native implementation of Johnson QPD family, explicit pdf
  skpro/distributions/qpd.py
  skpro/distributions/tests/test_qpd.py
Labels: enhancement, module:probability&simulation

#334 [ENH] fix distribution row/column convention in `CyclicBoosting`
  skpro/regression/cyclic_boosting.py
Labels: enhancement, module:regression

#329 [MNT] deprecation handling for `CyclicBoosting`
  skpro/regression/cyclic_boosting.py
Labels: module:regression, documentation

#333 [MNT] fix repository variables in changelog generator
  build_tools/changelog.py
Labels: maintenance, documentation

#312 Release 2.3.0
  README.md
  docs/source/_static/switcher.json
  docs/source/changelog.rst
  pyproject.toml
  skpro/__init__.py
Labels: maintenance, release

#336 [DOC] Release 2.3.0 notes - typo fixes
  docs/source/changelog.rst
Labels: documentation

#338 [DOC] Fix typos throughout the codebase
  .all-contributorsrc
  docs/introduction.rst
  docs/source/changelog.rst
  docs/source/conf.py
  docs/source/contribute/code_of_conduct.rst
  docs/source/developer_guide/dependencies.rst
  docs/source/developer_guide/deprecation.rst
  docs/source/developer_guide/reviewer_guide.rst
  docs/source/installation.rst
  examples/01_skpro_intro.ipynb
  examples/02_skpro_survival.ipynb
  examples/03_skpro_distributions.ipynb
  extension_templates/regression.py
  extension_templates/survival.py
  skpro/datatypes/_convert.py
  skpro/datatypes/_convert_utils/_convert.py
  skpro/datatypes/tests/test_convert_to.py
  skpro/distributions/base/_base.py
  skpro/distributions/delta.py
  skpro/distributions/empirical.py
  skpro/metrics/base.py
  skpro/regression/cyclic_boosting.py
  skpro/regression/density.py
  skpro/regression/tests/test_cyclic_boosting.py
  skpro/survival/ensemble/_survforest_sksurv.py
  skpro/tests/scenarios/scenarios_getter.py
  skpro/utils/_maint/tests/test_show_versions.py
  skpro/utils/numpy.py
Labels: documentation

#339 [MNT] isolate imports in `changelog.py` build util
  build_tools/changelog.py
Labels: maintenance

#345 [BUG] fix `test_run_test_for_class` test logic
  skpro/tests/tests/test_test_utils.py
Labels: bug, module:tests

#344 [BUG] fix `random_state` handling in `BootstrapRegressor`
  skpro/regression/bootstrap.py
Labels: bug, module:regression

#348 [ENH] make `get_packages_with_changed_specs` safe to mutation of return
  skpro/utils/git_diff.py
Labels: enhancement, module:tests

#352 [BUG] fix `spl` index when subsetting `Empirical` distribution via `iat`
  skpro/distributions/empirical.py
  skpro/distributions/tests/test_empirical.py
Labels: bug, module:probability&simulation

#353 [ENH] improved default function to plot via `BaseDistribution.plot`, depending on distribution type
  skpro/distributions/base/_base.py
Labels: enhancement, module:probability&simulation

#347 [ENH] iid array distribution
  docs/source/api_reference/distributions.rst
  skpro/distributions/__init__.py
  skpro/distributions/compose/__init__.py
  skpro/distributions/compose/_iid.py
Labels: enhancement, module:probability&simulation

#351 [ENH] Correct algorithm in `EnbpiRegressor`
  skpro/regression/enbpi.py
Labels: enhancement, module:regression

#355 [ENH] Gamma Distribution
  docs/source/api_reference/distributions.rst
  skpro/distributions/__init__.py
  skpro/distributions/gamma.py
Labels: enhancement, module:probability&simulation, implementing algorithms

#359 [DOC] minor docs improvements
  README.md
  docs/source/index.rst
  extension_templates/distributions.py
  skpro/distributions/base/_base.py
  skpro/distributions/base/_delegate.py
  skpro/distributions/compose/_iid.py
  skpro/distributions/empirical.py
  skpro/distributions/mixture.py
Labels: documentation

#360 [DOC] fix download shields in readme
  README.md
Labels: documentation

#361 [DOC] fixing download shields in README
  README.md
Labels: documentation

#362 [DOC] fixing download shields in README
  README.md
Labels: documentation

#356 [ENH] Alpha distribution
  docs/source/api_reference/distributions.rst
  skpro/distributions/__init__.py
  skpro/distributions/alpha.py
Labels: enhancement, module:probability&simulation, interfacing algorithms

#80 [MNT] remove legacy base modules
  skpro/base/old_base.py
  skpro/regression/baselines/__init__.py
  skpro/regression/baselines/density.py
  skpro/regression/parametric/parametric.py
  skpro/regression/vendors/__init__.py
  skpro/regression/vendors/pymc.py
  skpro/tests/test_base.py
  skpro/tests/test_baselines.py
  skpro/tests/test_vendors.py
Labels: maintenance, module:base-framework

#365 [MNT] 2.3.0 deprecations and change actions
  skpro/datatypes/_check.py
  skpro/model_selection/_tuning.py
Labels: maintenance, release

#366 [MNT] [Dependabot](deps): Update scikit-base requirement from <0.8.0,>=0.6.1 to >=0.6.1,<0.9.0
  pyproject.toml
  skpro/registry/_lookup.py
Labels: maintenance

#364 Release 2.3.1
  README.md
  docs/source/_static/switcher.json
  docs/source/changelog.rst
  pyproject.toml
  skpro/__init__.py
Labels: maintenance, release

#368 [DOC] fix typo in survival models API reference
  docs/source/api_reference/survival.rst
Labels: documentation, module:survival&time-to-event

#363 [ENH] Half Normal Distribution
  docs/source/api_reference/distributions.rst
  skpro/distributions/__init__.py
  skpro/distributions/halfnormal.py
Labels: enhancement, module:probability&simulation

#320 [MNT] Deprecation message for `CyclicBoosting` changes
  skpro/distributions/qpd.py
Labels: maintenance, module:regression
