Repository sktime/skpro, pull requests merged in 2024-04, with the labels that each got.

#226 [ENH] Poisson distribution
  docs/source/api_reference/distributions.rst
  skpro/distributions/__init__.py
  skpro/distributions/poisson.py
Labels: module:probability&simulation, implementing algorithms

#234 [ENH] add test parameters to probabilistic metrics, docs improvement
  skpro/metrics/_classes.py
  skpro/metrics/tests/test_distr_metrics.py
Labels: enhancement, module:probability&simulation, documentation

#233 [ENH] make `Empirical` distribution compatible with multi-index rows
  skpro/distributions/empirical.py
Labels: enhancement, module:probability&simulation

#238 [DOC] add julian-fong to `all-contributorsrc`
  .all-contributorsrc
  skpro/survival/compose/_reduce_cond_unc.py
Labels: documentation

#243 [MNT] Fix broken api source links in latest docs version
  docs/source/conf.py
Labels: maintenance, documentation

#237 [ENH] adapter to `scikit-survival`, all distributional survival regressors interfaced
  docs/source/api_reference/survival.rst
  pyproject.toml
  skpro/registry/_tags.py
  skpro/survival/adapters/__init__.py
  skpro/survival/adapters/sksurv.py
  skpro/survival/coxph/__init__.py
  skpro/survival/coxph/_coxnet_sksurv.py
  skpro/survival/coxph/_coxph_sksurv.py
  skpro/survival/coxph/_coxph_statsmodels.py
  skpro/survival/ensemble/__init__.py
  skpro/survival/ensemble/_grad_boost_sksurv.py
  skpro/survival/ensemble/_survforest_sksurv.py
  skpro/survival/tree/__init__.py
  skpro/survival/tree/_tree_sksurv.py
Labels: enhancement, interfacing algorithms, module:survival&time-to-event

#239 [ENH] add `len` of `BaseDistribution`, test `shape`, `len`, indices
  skpro/distributions/base.py
  skpro/distributions/tests/test_all_distrs.py
Labels: enhancement, module:probability&simulation

#245 [ENH] refactor test scenario creation to be lazy rather than on module load
  skpro/tests/scenarios/scenarios_regressor_proba.py
Labels: enhancement, module:tests

#242 [ENH] Weibull distribution
  docs/source/api_reference/distributions.rst
  skpro/distributions/__init__.py
  skpro/distributions/weibull.py
Labels: enhancement, module:probability&simulation

#247 [ENH] adapter to `lifelines`, most distributional survival regressors interfaced
  docs/source/api_reference/survival.rst
  pyproject.toml
  skpro/survival/adapters/_common.py
  skpro/survival/adapters/lifelines.py
  skpro/survival/adapters/sksurv.py
  skpro/survival/additive/__init__.py
  skpro/survival/additive/_aalen_lifelines.py
  skpro/survival/aft/__init__.py
  skpro/survival/aft/_aft_lifelines_weibull.py
  skpro/survival/coxph/__init__.py
  skpro/survival/coxph/_coxph_lifelines.py
Labels: enhancement, interfacing algorithms, module:survival&time-to-event

#218 [ENH] Lognormal probability distribution
  skpro/distributions/__init__.py
  skpro/distributions/lognormal.py
Labels: enhancement, module:probability&simulation

#241 [ENH] Logistic distribution
  .all-contributorsrc
  docs/source/api_reference/distributions.rst
  skpro/distributions/__init__.py
  skpro/distributions/logistic.py
Labels: enhancement, module:probability&simulation

#236 [ENH] empirical quantile parameterized distribution
  docs/source/api_reference/distributions.rst
  skpro/distributions/__init__.py
  skpro/distributions/qpd_empirical.py
  skpro/regression/multiquantile.py
Labels: enhancement, module:probability&simulation, module:regression, implementing algorithms

#256 [ENH] remove stray `_get_bc_params` from `LogNormal`
  skpro/distributions/lognormal.py
Labels: enhancement, module:probability&simulation

#252 [ENH] delegator class for distributions
  skpro/distributions/base/__init__.py
  skpro/distributions/base/_base.py
  skpro/distributions/base/_delegate.py
Labels: enhancement, module:probability&simulation

#194 [BUG] bugfixes to QPD distributions - `QPD_U`, `QPD_S`
  skpro/distributions/base/_base.py
  skpro/distributions/qpd.py
  skpro/distributions/tests/test_all_distrs.py
Labels: bug, module:probability&simulation

#255 [DOC] docstring with mathematical description for `QPD_Empirical`
  skpro/distributions/qpd_empirical.py
Labels: module:probability&simulation, documentation

#253 [ENH] Johnson QP-distributions - add some missing capability tags
  skpro/distributions/qpd.py
Labels: enhancement, module:probability&simulation

#259 [ENH] Fisk distribution aka log-logistic distribution
  docs/source/api_reference/distributions.rst
  skpro/distributions/__init__.py
  skpro/distributions/fisk.py
  skpro/survival/ensemble/_survforest_sksurv.py
Labels: enhancement, module:probability&simulation, interfacing algorithms

#261 [BUG] fixes to lognormal distribution
  skpro/distributions/lognormal.py
Labels: bug, module:probability&simulation

#228 Release 2.2.2
  README.md
  docs/source/_static/switcher.json
  docs/source/changelog.rst
  pyproject.toml
  skpro/__init__.py
Labels: maintenance, release

#262 [DOC] add `zenodo` citation badge in README
  README.md
  docs/source/changelog.rst
Labels: documentation

#263 [DOC] fix typo in changelog link
  docs/source/changelog.rst
Labels: documentation

#264 [DOC] typo fixes in Fisk AFT docstring
  skpro/survival/aft/_aft_lifelines_fisk.py
Labels: documentation, module:survival&time-to-event

#268 [DOC] fix minor typos in the changelog
  docs/source/changelog.rst
Labels: documentation

#270 [DOC] fixes to extension templates
  extension_templates/regression.py
  extension_templates/survival.py
Labels: module:regression, documentation, module:survival&time-to-event

#271 [DOC] remove legacy examples
  examples/custom_model.py
  examples/parametric/bagging.py
  examples/parametric/hyperparameters.py
  examples/parametric/simple.py
  examples/parametric/workflow.py
  examples/simple.py
  examples/vendors/pymc.py
  examples/workflow.py
Labels: documentation

#272 [MNT] move GHA runners consistently to `ubuntu-latest`, `windows-latest`, `macos-13`
  .github/workflows/test.yml
Labels: maintenance

#265 [ENH] probability distributions - boilerplate refactor
  extension_templates/distributions.py
  extension_templates/regression.py
  extension_templates/survival.py
  skpro/distributions/base/_base.py
  skpro/distributions/empirical.py
  skpro/distributions/fisk.py
  skpro/distributions/laplace.py
  skpro/distributions/logistic.py
  skpro/distributions/lognormal.py
  skpro/distributions/normal.py
  skpro/distributions/t.py
  skpro/distributions/tests/test_base_scalar.py
  skpro/distributions/weibull.py
  skpro/registry/_tags.py
Labels: enhancement, module:probability&simulation

#274 [ENH] `at` and `iat` subsetters for distributions
  skpro/distributions/base/_base.py
  skpro/distributions/tests/test_proba_basic.py
  skpro/registry/_tags.py
Labels: module:probability&simulation, implementing framework

#276 [ENH] probability distirbutions: convenience feature to coerce `index` and `columns` to `pd.Index`
  skpro/distributions/base/_base.py
  skpro/distributions/tests/test_proba_basic.py
Labels: enhancement, module:probability&simulation

#279 [ENH] scalar test cases for probability distributions
  skpro/distributions/base/_base.py
  skpro/distributions/fisk.py
  skpro/distributions/laplace.py
  skpro/distributions/logistic.py
  skpro/distributions/lognormal.py
  skpro/distributions/t.py
  skpro/distributions/weibull.py
Labels: enhancement, module:probability&simulation

#280 [DOC] correcting 2024 changelog dates
  README.md
  docs/source/changelog.rst
Labels: documentation

#275 [ENH] probability distributions: illustrative and didactic plotting functionality
  skpro/distributions/base/_base.py
  skpro/distributions/tests/test_proba_basic.py
Labels: enhancement, module:probability&simulation

#223 [ENH] Uniform Continuous distribution
  skpro/distributions/__init__.py
  skpro/distributions/uniform.py
Labels: enhancement, module:probability&simulation, implementing algorithms

#284 [DOC] add missing contributors - @an20805, @duydl, @sukjingitsit
  .all-contributorsrc
Labels: documentation

#217 [ENH] Chi-Squared Distribution
  docs/source/api_reference/distributions.rst
  skpro/distributions/__init__.py
  skpro/distributions/chi_squared.py
Labels: enhancement, module:probability&simulation, implementing algorithms

#213 [ENH] interfacing Poisson regressor from sklearn
  docs/source/api_reference/regression.rst
  skpro/regression/linear/__init__.py
  skpro/regression/linear/_sklearn.py
  skpro/regression/linear/_sklearn_poisson.py
Labels: enhancement, module:regression

#286 [ENH] fix `Empirical` index to be `pd.MultiIndex` for hierarchical data index
  skpro/distributions/empirical.py
Labels: bug, module:probability&simulation
