Repository sktime/skpro, pull requests merged in 2024-03, with the labels that each got.

#210 ivarzap [BUG] fix missing location/scale in `TDistribution`
  skpro/distributions/t.py
Labels: bug, module:probability&simulation

#211 Release 2.2.1
  README.md
  docs/source/_static/switcher.json
  docs/source/changelog.rst
  pyproject.toml
  skpro/__init__.py
Labels: maintenance, release

#225 Revert "[MNT] point readthedocs `json` switcher variable to GitHub"
  docs/source/conf.py
Labels: documentation

#222 [ENH] `GaussianRegressor` using statsmodels `GLM` with gaussian link
  docs/source/api_reference/regression.rst
  skpro/regression/linear/__init__.py
  skpro/regression/linear/_glm.py
Labels: enhancement, module:regression, interfacing algorithms
