Repository sktime/skpro, pull requests merged in 2025-07, with the labels that each got.

#557 [ENH] Adds `Hurdle` and `LeftTruncatedDiscrete` distributions
  .all-contributorsrc
  docs/source/api_reference/distributions.rst
  skpro/distributions/__init__.py
  skpro/distributions/hurdle.py
  skpro/distributions/left_truncated.py
  skpro/distributions/truncated.py
Labels: enhancement, module:probability&simulation

#558 [ENH] probabilistic `TransformedTargetRegressor`
  docs/source/api_reference/regression.rst
  skpro/regression/compose/__init__.py
  skpro/regression/compose/_ttr.py
Labels: enhancement, module:regression, implementing algorithms

#562 [ENH] verbose printout for `check_estimator` in `raise_exceptions` case
  skpro/utils/estimator_checks.py
Labels: enhancement, module:tests

#561 Release 2.9.2
  README.md
  docs/source/_static/switcher.json
  docs/source/changelog.rst
  pyproject.toml
  skpro/__init__.py
Labels: maintenance, release

#564 [ENH] `MAPIE<1.0` bound for legacy `MapieRegressor`
  docs/source/changelog.rst
  skpro/regression/mapie.py
Labels: enhancement, module:regression

#565 [ENH] improving stability of test parameter settings for `CoxPHlifelines`
  skpro/survival/coxph/_coxph_lifelines.py
Labels: enhancement, module:survival&time-to-event

#570 [BUG] correctly set tags for `Poisson` distribution
  skpro/distributions/poisson.py
Labels: bug, module:probability&simulation
