Repository sktime/skpro, pull requests merged in 2025-08, with the labels that each got.

#574 [BUG] fix `pdf` and `pmf` default return type in scalar case
  skpro/distributions/base/_base.py
  skpro/distributions/tests/test_base_scalar.py
Labels: bug, module:probability&simulation

#577 [ENH] Moves epsilo offset logic to `TruncatedDistribution` from `Hurdle`
  skpro/distributions/hurdle.py
  skpro/distributions/truncated.py
Labels: enhancement, module:probability&simulation

#575 [DOC] fix badge link to license in README
  README.md
Labels: documentation

#578 [DOC] corrected and improved docstring for `MeanScale` distribution family
  skpro/distributions/meanscale.py
Labels: module:probability&simulation, documentation

#585 [BUG] fix `HistBinnedRegressor.predict` return type
  skpro/regression/binned/_sklearn_bin_regressor.py
  skpro/regression/tests/test_all_regressors.py
Labels: bug, module:regression
