Repository sktime/skpro, pull requests merged in 2025-01, with the labels that each got.

#515 [ENH] minor reorder or Bayesian regressors
  docs/source/api_reference/regression.rst
  skpro/regression/bayesian/__init__.py
  skpro/regression/bayesian/_linear_conjugate.py
  skpro/regression/bayesian/_linear_mcmc.py
Labels: enhancement, module:regression

#518 [ENH] Erlang Distribution
  docs/source/api_reference/distributions.rst
  skpro/distributions/__init__.py
  skpro/distributions/erlang.py
Labels: enhancement, module:probability&simulation

#521 [DOC] extension templates: instruction preamble
  extension_templates/distributions.py
  extension_templates/regression.py
  extension_templates/survival.py
Labels: module:probability&simulation, module:regression, documentation, module:survival&time-to-event

#523 [DOC] improved docstring for the `TDistribution`
  skpro/distributions/t.py
Labels: module:probability&simulation, documentation

#522 [ENH] interface for `xgboostlss` regressors
  docs/source/api_reference/regression.rst
  pyproject.toml
  skpro/distributions/t.py
  skpro/regression/xgboostlss.py
Labels: enhancement, module:regression, interfacing algorithms

#512 [ENH] Skew-Normal Distribution
  docs/source/api_reference/distributions.rst
  skpro/distributions/__init__.py
  skpro/distributions/skew_normal.py
Labels: module:probability&simulation, implementing algorithms

#524 Release 2.9.0
  README.md
  docs/source/_static/switcher.json
  docs/source/changelog.rst
  pyproject.toml
  skpro/__init__.py
Labels: maintenance, release
